<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="16" failures="0" hostname="ab-VM" name="autolib" skipped="0" tests="16" time="229.892" timestamp="2023-09-20T12:04:36.565421"><testcase classname="" name="AncillaryInspectorTests.test_anc_location" time="0.000"><error message="collection failure">../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f&quot;Failed to obtain an IP address for Hostname: {self._hostname}&quot;)
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py</error></testcase><testcase classname="" name="Audio.test_aes" time="0.000"><error message="collection failure">../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f&quot;Failed to obtain an IP address for Hostname: {self._hostname}&quot;)
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py</error></testcase><testcase classname="" name="Audio.test_enable_disable_audio_groups" time="0.000"><error message="collection failure">../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f&quot;Failed to obtain an IP address for Hostname: {self._hostname}&quot;)
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py</error></testcase><testcase classname="" name="CRC_Checks.test_standard_crc" time="0.000"><error message="collection failure">../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f&quot;Failed to obtain an IP address for Hostname: {self._hostname}&quot;)
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py</error></testcase><testcase classname="" name="NMOS.test_flowconfig_manipulation" time="0.000"><error message="collection failure">NMOS/test_flowconfig_manipulation.py:223: in &lt;module&gt;
    preset_callback: Callable[[dict, str], dict]):
E   TypeError: &apos;ABCMeta&apos; object is not subscriptable</error></testcase><testcase classname="" name="NMOS.test_nmos_ids" time="0.000"><error message="collection failure">../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f&quot;Failed to obtain an IP address for Hostname: {self._hostname}&quot;)
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py</error></testcase><testcase classname="" name="Signal.test_basic_crc_check" time="0.000"><error message="collection failure">../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f&quot;Failed to obtain an IP address for Hostname: {self._hostname}&quot;)
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py</error></testcase><testcase classname="" name="Signal.test_generate_same_standards" time="0.000"><error message="collection failure">../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f&quot;Failed to obtain an IP address for Hostname: {self._hostname}&quot;)
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py</error></testcase><testcase classname="" name="Signal.test_generator_test_patterns" time="0.000"><error message="collection failure">../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f&quot;Failed to obtain an IP address for Hostname: {self._hostname}&quot;)
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py</error></testcase><testcase classname="Signal.test_sdi_io" name="TestSdiInputOutput" time="0.000"><error message="collection failure">../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f&quot;Failed to obtain an IP address for Hostname: {self._hostname}&quot;)
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py</error></testcase><testcase classname="SmokeTest.ip_2022_6_smoke_test" name="TestIP20226Smoke" time="0.000"><error message="collection failure">../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f&quot;Failed to obtain an IP address for Hostname: {self._hostname}&quot;)
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py</error></testcase><testcase classname="SmokeTest.ip_2110_smoke_test" name="TestIP2110Smoke" time="0.000"><error message="collection failure">../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f&quot;Failed to obtain an IP address for Hostname: {self._hostname}&quot;)
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py</error></testcase><testcase classname="SmokeTest.sdi_smoke_test" name="TestSDIModesSmoke" time="0.000"><error message="collection failure">../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f&quot;Failed to obtain an IP address for Hostname: {self._hostname}&quot;)
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py</error></testcase><testcase classname="" name="SmokeTest.test_presets" time="0.000"><error message="collection failure">../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f&quot;Failed to obtain an IP address for Hostname: {self._hostname}&quot;)
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py</error></testcase><testcase classname="System.test_dual_flash" name="TestDualFlashSuite" time="0.000"><error message="collection failure">../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f&quot;Failed to obtain an IP address for Hostname: {self._hostname}&quot;)
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py</error></testcase><testcase classname="" name="System.test_upgrades" time="0.000"><error message="collection failure">../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f&quot;Failed to obtain an IP address for Hostname: {self._hostname}&quot;)
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py</error></testcase></testsuite></testsuites>