============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-5.4.2, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/arthur/projects/qx_sw/tests, inifile: pytest.ini
plugins: timeout-1.4.2, timestamper-0.0.9
collecting ... collected 0 items / 16 errors

==================================== ERRORS ====================================
________ ERROR collecting AncillaryInspectorTests/test_anc_location.py _________
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f"Failed to obtain an IP address for Hostname: {self._hostname}")
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py
______________________ ERROR collecting Audio/test_aes.py ______________________
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f"Failed to obtain an IP address for Hostname: {self._hostname}")
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py
__________ ERROR collecting Audio/test_enable_disable_audio_groups.py __________
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f"Failed to obtain an IP address for Hostname: {self._hostname}")
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py
_______________ ERROR collecting CRC_Checks/test_standard_crc.py _______________
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f"Failed to obtain an IP address for Hostname: {self._hostname}")
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py
____________ ERROR collecting NMOS/test_flowconfig_manipulation.py _____________
NMOS/test_flowconfig_manipulation.py:223: in <module>
    preset_callback: Callable[[dict, str], dict]):
E   TypeError: 'ABCMeta' object is not subscriptable
____________________ ERROR collecting NMOS/test_nmos_ids.py ____________________
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f"Failed to obtain an IP address for Hostname: {self._hostname}")
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py
_______________ ERROR collecting Signal/test_basic_crc_check.py ________________
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f"Failed to obtain an IP address for Hostname: {self._hostname}")
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py
___________ ERROR collecting Signal/test_generate_same_standards.py ____________
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f"Failed to obtain an IP address for Hostname: {self._hostname}")
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py
___________ ERROR collecting Signal/test_generator_test_patterns.py ____________
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f"Failed to obtain an IP address for Hostname: {self._hostname}")
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py
____________________ ERROR collecting Signal/test_sdi_io.py ____________________
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f"Failed to obtain an IP address for Hostname: {self._hostname}")
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py
______________ ERROR collecting SmokeTest/ip_2022_6_smoke_test.py ______________
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f"Failed to obtain an IP address for Hostname: {self._hostname}")
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py
_______________ ERROR collecting SmokeTest/ip_2110_smoke_test.py _______________
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f"Failed to obtain an IP address for Hostname: {self._hostname}")
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py
_________________ ERROR collecting SmokeTest/sdi_smoke_test.py _________________
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f"Failed to obtain an IP address for Hostname: {self._hostname}")
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py
__________________ ERROR collecting SmokeTest/test_presets.py __________________
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f"Failed to obtain an IP address for Hostname: {self._hostname}")
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py
__________________ ERROR collecting System/test_dual_flash.py __________________
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f"Failed to obtain an IP address for Hostname: {self._hostname}")
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py
___________________ ERROR collecting System/test_upgrades.py ___________________
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../.local/lib/python3.8/site-packages/_pytest/python.py:246: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/lib/python3.8/site-packages/_pytest/python.py:413: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:113: in pytest_generate_tests
    unit = make_qx(qx_generator)
../../../.local/lib/python3.8/site-packages/autolib/factory.py:19: in make_qx
    qx = Qx(hostname, http_session)
../../../.local/lib/python3.8/site-packages/autolib/models/qxseries/qx.py:120: in __init__
    raise QxException(f"Failed to obtain an IP address for Hostname: {self._hostname}")
E   autolib.models.qxseries.qxexception.QxException: Failed to obtain an IP address for Hostname: Audio/test_enable_disable_audio_groups.py
------- generated xml file: /home/arthur/projects/qx_sw/tests/.junit.xml -------
=========================== short test summary info ============================
ERROR AncillaryInspectorTests/test_anc_location.py - autolib.models.qxseries....
ERROR Audio/test_aes.py - autolib.models.qxseries.qxexception.QxException: Fa...
ERROR Audio/test_enable_disable_audio_groups.py - autolib.models.qxseries.qxe...
ERROR CRC_Checks/test_standard_crc.py - autolib.models.qxseries.qxexception.Q...
ERROR NMOS/test_flowconfig_manipulation.py - TypeError: 'ABCMeta' object is n...
ERROR NMOS/test_nmos_ids.py - autolib.models.qxseries.qxexception.QxException...
ERROR Signal/test_basic_crc_check.py - autolib.models.qxseries.qxexception.Qx...
ERROR Signal/test_generate_same_standards.py - autolib.models.qxseries.qxexce...
ERROR Signal/test_generator_test_patterns.py - autolib.models.qxseries.qxexce...
ERROR Signal/test_sdi_io.py::TestSdiInputOutput - autolib.models.qxseries.qxe...
ERROR SmokeTest/ip_2022_6_smoke_test.py::TestIP20226Smoke - autolib.models.qx...
ERROR SmokeTest/ip_2110_smoke_test.py::TestIP2110Smoke - autolib.models.qxser...
ERROR SmokeTest/sdi_smoke_test.py::TestSDIModesSmoke - autolib.models.qxserie...
ERROR SmokeTest/test_presets.py - autolib.models.qxseries.qxexception.QxExcep...
ERROR System/test_dual_flash.py::TestDualFlashSuite - autolib.models.qxseries...
ERROR System/test_upgrades.py - autolib.models.qxseries.qxexception.QxExcepti...
!!!!!!!!!!!!!!!!!!! Interrupted: 16 errors during collection !!!!!!!!!!!!!!!!!!!
======================== 16 errors in 229.96s (0:03:49) ========================
